macro_tasks:
  macro_task_0:
      - path:
          - [0.0, 0.0, 0.0]
        move:
          "sleep"
      - path:
          - [0.0, 750.0, 0.0]
        move:
          "sleep"
      - path:
          - [750.0, 750.0, 0.0]
        move:
          "throw"
      - path:
          - [750.0, 0.0, 0.0]
        move:
          "sleep"
  macro_task_1: 
      - path:
          - [0.0, 1000.0, 0.0]
        move:
          "sleep"
      - path:
          - [1000.0, 1000.0, 0.0]
        move:
          "sleep"
